export enum EventType {

    FETCH_START = "FETCH_START",
    FETCH_FAIL = "FETCH_FAIL",
    FETCH_DONE = "FETCH_DONE",

    ITEM_ADDED = "ITEM_ADDED",
    ITEM_REMOVED = "ITEM_REMOVED",
    ITEM_MODIFIED = "ITEM_MODIFIED",

    DATA_REORDERED = "DATA_REORDERED",
    DATA_FILTERED = "DATA_FILTERED",
    DATA_FILTER_CLEARED = "DATA_FILTER_CLEARED"

}